version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

  db:
    image: postgres:10.11-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    restart: always
    build:
      context: ./backend
    entrypoint: ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres-data:
  static:
  media: