# Generated by Django 3.2.6 on 2021-08-29 11:39

import apps.upload_files.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'upload_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата и время начала загрузки'
                    ),
                ),
                (
                    'finish_date',
                    models.DateTimeField(
                        blank=True, verbose_name='Дата и время окончания загрузки'
                    ),
                ),
                (
                    'current_status',
                    models.CharField(
                        choices=[
                            ('start', 'Начало загрузки'),
                            ('processed', 'Обработка'),
                            ('complete', 'Обработан'),
                            ('error', 'Ошибка'),
                        ],
                        default='start',
                        max_length=10,
                    ),
                ),
                (
                    'result',
                    models.CharField(blank=True, max_length=20, verbose_name='результат обработки'),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to='files/',
                        validators=[apps.upload_files.validators.file_validate],
                        verbose_name='файл',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Обработка файла',
                'verbose_name_plural': 'Обработка файлов',
                'ordering': ('-upload_date',),
            },
        ),
    ]
