# Generated by Django 3.2.6 on 2021-08-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='finish_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время окончания загрузки'),
        ),
    ]
